name: default

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    container: mukn/glow:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: ./scripts/ci.ss before-build
      - run: ./scripts/ci.ss build
      - env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: ./scripts/ci.ss after-build
